language: node_js
node_js:
  - "4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "qDcyE26gN41kEzj9L0KvF4ssPHog5IzlCzF3KBtolSryYVwzQfWXht+LQEMpNJZPKxntQfoU/Mf1y94skroDYc7e/bmnpM4hgz5owQipDCEQVI9TryUxbbrF6Pts5DYVY2qJg0rHsuXMaUhBXaP4bukfBV1y73hfuN4t13zBolesxJb409g6cVkw8mdub1RjyJpsJMm6guPC/jHOudEakmfR/DVIV1ruVK+o/g6QENBIqFBgeVEDKGWf/Z38WzOHsjrOZRpv51x4A9bNhWcVEnSG0PIaAVZVQtr4AJHAeWh6rTmLzA89XaVcFZX1uJBHHbLUuwOqMF/MWY70YjwQHHwEWias4RrAsI/pQPehy/MJk2EO7V3iBHbGKGO4nWwKZ9+CbLkw/U5BPJ6tP/XTOtPLbj/P9jVyuYbPetnw30nxssoXcb+xfXwyHz/uoVX/JIOOLVNwr4ktzRz8Z0CfRRCYMdEg/YHz23FkKXI9+lC5S7BCs95+yrwd2uOgIzuZrk5ftiEGJqZG6EN4wCux4nzBsIjstquqlSQkDJj3qnJENI7zvJz9yKktiPzZr6XjkLLbWPrVNLcpHyAF1QlgJSpBeff63RftKoGK8UyssOxZMJYkVAmfdheAPLsHnEHf2e2fy9Cx+Rh2VN/nv5uzm0azgnDYXrfhkg9qeG8+u1M="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

before_script:
- npm run lint
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
