baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'OpenAQ Design System'
theme = 'openaq-design-system-docs'

[markup.goldmark.renderer]
  unsafe = true 

[markup]
  [markup.highlight]
    style = 'manni'