name: build docs

on:
  push:
    branches:
      - v-4.0.0
jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
            
      - name: Build
        working-directory: ./docs
        uses: openaq/hugo-build-action@main

      - name: Deploy
        working-directory: ./docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public